common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password:

development:
  <<: *common
  database: auximmo_development

test:
  <<: *common
  database: auximmo_test<%= ENV['TEST_ENV_NUMBER'] %>
